[2017-12-20 21:06:34.518] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-20 21:21:36.688] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-21 15:45:07.738] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-22 15:17:23.653] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-22 19:31:55.445] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-22 19:47:16.647] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-22 21:31:46.250] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2017-12-30 11:34:51.897] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/
[2017-12-30 11:34:53.911] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2017-12-30 11:35:07.728] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 599: Timeout while connecting)
[2017-12-30 11:35:13.329] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 599: Timeout while connecting)
[2017-12-30 11:37:46.566] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 599: Timeout while connecting)
[2017-12-30 11:38:12.676] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 599: Timeout while connecting)
[2017-12-30 16:21:26.167] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 599: Timeout while connecting)
[2017-12-30 16:21:26.271] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 599: Timeout while connecting)
[2017-12-30 16:21:36.485] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-02 18:42:47.729] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-02 20:59:54.330] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-03 21:58:05.505] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-09 20:20:09.728] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/
[2018-01-09 20:20:10.248] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2018-01-09 20:20:20.442] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-09 20:20:57.740] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/
[2018-01-09 20:20:57.789] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2018-01-09 20:21:09.755] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 599: Timeout while connecting)
[2018-01-09 20:21:09.799] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 599: Timeout while connecting)
[2018-01-09 20:21:21.766] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 599: Timeout during request)
[2018-01-09 20:21:21.809] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 599: Timeout while connecting)
[2018-01-09 20:21:32.610] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-10 02:25:52.608] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2018-01-10 02:26:02.789] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-10 23:39:43.069] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2018-01-10 23:39:53.250] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-11 00:58:32.963] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/
[2018-01-11 00:58:43.207] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.websocket.nio.works:443/ (HTTP 503: Service Temporarily Unavailable)
[2018-01-11 00:59:09.085] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Disconnected from Websocket Herver: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws
[2018-01-11 00:59:19.328] NIO [WARNING] [UseWarning.pubkeeper.utils.websocket] Connection Failure: wss://5a006ff2-7153-4bc6-9152-41f13d7934fd.pubkeeper.nio.works:443/ws (HTTP 503: Service Temporarily Unavailable)
[2018-01-11 00:59:29.496] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-16 22:50:55.091] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:48:50.938] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:51:08.357] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:51:08.477] NIO [ERROR] [pubkeeper.protocol.v1] Action error ('NoneType' object has no attribute 'on_connected')
[2018-01-17 15:51:08.487] NIO [ERROR] [UseWarning.pubkeeper.utils.websocket] Error reading message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 57, in on_message
    self.handlers[Packet(packet)](**payload)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 138, in on_patron_notify
    brewer.new_patrons(patrons)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/brewer/brewer.py", line 63, in new_patrons
    patron['brew'])
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/brew/websocket/brew.py", line 118, in start_brewer
    self._protocol.on_connected(self._connection, topic)
AttributeError: 'NoneType' object has no attribute 'on_connected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/utils/websocket.py", line 161, in read_messages
    self._on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/client.py", line 135, in _on_message
    self.protocol.on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 65, in on_message
    message='Action error ({0})'.format(e)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 55, in write_message
    self._connection.write_message(msg, binary=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 1136, in write_message
    return self.protocol.write_message(message, binary)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 778, in write_message
    message = tornado.escape.utf8(message)
  File "/usr/local/lib/python3.5/dist-packages/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <class 'pubkeeper.protocol.v1.packet.ErrorPacket'>
[2018-01-17 15:51:09.066] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:51:09.177] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:51:09.183] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:51:13.219] NIO [INFO] [UseWarning.Log] {"authorized": ["Tyler\u2019s MacBook Pro", "May\u2019s MacBook Pro", "Bedroom peaker", "May\u2019s iPhone", "XboxOne", "Phone Boy", "Pixel 2", "nothing"], "device": {"id": "15b2f70b7b614dbf3d2bb840169e325bdecd59f5", "is_active": true, "is_restricted": false, "name": "Web Player (Firefox)", "type": "Computer", "volume_percent": 100}, "token": "BQAHJrgvvANGdRAQ_UT-YfyqZtE4ND0EieGOkzb-x8mUAPQv_hpRctFV8QOMQQZ2Zui9HCGWZ569IDLgbkMGQulFGY3r3mHC2uXpCHHxsybriEZBnt91e12N1cmZCZubt_xJIsQEEUdDDOxQQJkIt9B4oNWucrCAMlDqxw9KIbmNe3E"}
[2018-01-17 15:51:16.181] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:51:16.204] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 15:51:16.252] NIO [WARNING] [UseWarning.ThreadedPoolExecutorRouter] Block Router is stopped, discarding signal notification from block: SubBadAuth
[2018-01-17 15:51:16.262] NIO [WARNING] [UseWarning.ThreadedPoolExecutorRouter] Block Router is stopped, discarding signal notification from block: SubBadAuth
[2018-01-17 15:51:57.785] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:51:57.922] NIO [ERROR] [pubkeeper.protocol.v1] Action error ('NoneType' object has no attribute 'on_connected')
[2018-01-17 15:51:57.930] NIO [ERROR] [UseWarning.pubkeeper.utils.websocket] Error reading message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 57, in on_message
    self.handlers[Packet(packet)](**payload)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 138, in on_patron_notify
    brewer.new_patrons(patrons)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/brewer/brewer.py", line 63, in new_patrons
    patron['brew'])
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/brew/websocket/brew.py", line 118, in start_brewer
    self._protocol.on_connected(self._connection, topic)
AttributeError: 'NoneType' object has no attribute 'on_connected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/utils/websocket.py", line 161, in read_messages
    self._on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/client.py", line 135, in _on_message
    self.protocol.on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 65, in on_message
    message='Action error ({0})'.format(e)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 55, in write_message
    self._connection.write_message(msg, binary=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 1136, in write_message
    return self.protocol.write_message(message, binary)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 778, in write_message
    message = tornado.escape.utf8(message)
  File "/usr/local/lib/python3.5/dist-packages/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <class 'pubkeeper.protocol.v1.packet.ErrorPacket'>
[2018-01-17 15:51:58.543] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:51:58.669] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:51:58.676] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:52:04.236] NIO [INFO] [UseWarning.Log] {"blue": "0", "device": "$device", "green": "0", "red": "255"}
[2018-01-17 15:52:04.465] NIO [INFO] [UseWarning.Log] {"blue": "0", "device": "$device", "green": "0", "red": "255"}
[2018-01-17 15:52:07.247] NIO [INFO] [UseWarning.Log] {"blue": "0", "device": "$device", "green": "0", "red": "255"}
[2018-01-17 15:52:07.879] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:52:07.886] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 15:52:47.727] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:52:47.851] NIO [ERROR] [pubkeeper.protocol.v1] Action error ('NoneType' object has no attribute 'on_connected')
[2018-01-17 15:52:47.858] NIO [ERROR] [UseWarning.pubkeeper.utils.websocket] Error reading message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 57, in on_message
    self.handlers[Packet(packet)](**payload)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 138, in on_patron_notify
    brewer.new_patrons(patrons)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/brewer/brewer.py", line 63, in new_patrons
    patron['brew'])
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/brew/websocket/brew.py", line 118, in start_brewer
    self._protocol.on_connected(self._connection, topic)
AttributeError: 'NoneType' object has no attribute 'on_connected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/utils/websocket.py", line 161, in read_messages
    self._on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/client.py", line 135, in _on_message
    self.protocol.on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 65, in on_message
    message='Action error ({0})'.format(e)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 55, in write_message
    self._connection.write_message(msg, binary=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 1136, in write_message
    return self.protocol.write_message(message, binary)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 778, in write_message
    message = tornado.escape.utf8(message)
  File "/usr/local/lib/python3.5/dist-packages/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <class 'pubkeeper.protocol.v1.packet.ErrorPacket'>
[2018-01-17 15:52:48.439] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:52:48.561] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:52:48.571] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:52:52.209] NIO [INFO] [UseWarning.Log] {"blue": "0", "device": {"id": "15b2f70b7b614dbf3d2bb840169e325bdecd59f5", "is_active": true, "is_restricted": false, "name": "Web Player (Firefox)", "type": "Computer", "volume_percent": 100}, "green": "0", "red": "255"}
[2018-01-17 15:52:52.391] NIO [INFO] [UseWarning.Log] {"blue": "0", "device": {"id": "15b2f70b7b614dbf3d2bb840169e325bdecd59f5", "is_active": true, "is_restricted": false, "name": "Web Player (Firefox)", "type": "Computer", "volume_percent": 100}, "green": "0", "red": "255"}
[2018-01-17 15:52:53.214] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:52:53.225] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 15:57:38.500] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:57:38.685] NIO [ERROR] [pubkeeper.protocol.v1] Action error ('NoneType' object has no attribute 'on_connected')
[2018-01-17 15:57:38.695] NIO [ERROR] [UseWarning.pubkeeper.utils.websocket] Error reading message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 57, in on_message
    self.handlers[Packet(packet)](**payload)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 138, in on_patron_notify
    brewer.new_patrons(patrons)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/brewer/brewer.py", line 63, in new_patrons
    patron['brew'])
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/brew/websocket/brew.py", line 118, in start_brewer
    self._protocol.on_connected(self._connection, topic)
AttributeError: 'NoneType' object has no attribute 'on_connected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/utils/websocket.py", line 161, in read_messages
    self._on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/client.py", line 135, in _on_message
    self.protocol.on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 65, in on_message
    message='Action error ({0})'.format(e)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 55, in write_message
    self._connection.write_message(msg, binary=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 1136, in write_message
    return self.protocol.write_message(message, binary)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 778, in write_message
    message = tornado.escape.utf8(message)
  File "/usr/local/lib/python3.5/dist-packages/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <class 'pubkeeper.protocol.v1.packet.ErrorPacket'>
[2018-01-17 15:57:39.226] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:57:39.360] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:57:39.368] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:58:26.233] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:58:26.241] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 15:58:31.546] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:58:32.179] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:58:32.286] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:58:32.292] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:58:38.562] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:58:38.570] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 15:58:53.702] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 15:58:53.864] NIO [ERROR] [pubkeeper.protocol.v1] Action error ('NoneType' object has no attribute 'on_connected')
[2018-01-17 15:58:53.873] NIO [ERROR] [UseWarning.pubkeeper.utils.websocket] Error reading message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 57, in on_message
    self.handlers[Packet(packet)](**payload)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 138, in on_patron_notify
    brewer.new_patrons(patrons)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/brewer/brewer.py", line 63, in new_patrons
    patron['brew'])
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/brew/websocket/brew.py", line 118, in start_brewer
    self._protocol.on_connected(self._connection, topic)
AttributeError: 'NoneType' object has no attribute 'on_connected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/utils/websocket.py", line 161, in read_messages
    self._on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/client.py", line 135, in _on_message
    self.protocol.on_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/protocol.py", line 65, in on_message
    message='Action error ({0})'.format(e)
  File "/usr/local/lib/python3.5/dist-packages/pubkeeper/protocol/v1/handler.py", line 55, in write_message
    self._connection.write_message(msg, binary=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 1136, in write_message
    return self.protocol.write_message(message, binary)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 778, in write_message
    message = tornado.escape.utf8(message)
  File "/usr/local/lib/python3.5/dist-packages/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <class 'pubkeeper.protocol.v1.packet.ErrorPacket'>
[2018-01-17 15:58:54.442] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 15:58:54.564] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 15:58:54.574] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 15:58:55.527] NIO [INFO] [UseWarning.Log] {"authorized": ["Tyler\u2019s MacBook Pro", "May\u2019s MacBook Pro", "Bedroom peaker", "May\u2019s iPhone", "XboxOne", "Phone Boy", "Pixel 2", "nothing"], "device": {"id": "15b2f70b7b614dbf3d2bb840169e325bdecd59f5", "is_active": true, "is_restricted": false, "name": "Web Player (Firefox)", "type": "Computer", "volume_percent": 100}, "token": "BQAHJrgvvANGdRAQ_UT-YfyqZtE4ND0EieGOkzb-x8mUAPQv_hpRctFV8QOMQQZ2Zui9HCGWZ569IDLgbkMGQulFGY3r3mHC2uXpCHHxsybriEZBnt91e12N1cmZCZubt_xJIsQEEUdDDOxQQJkIt9B4oNWucrCAMlDqxw9KIbmNe3E"}
[2018-01-17 15:58:58.251] NIO [INFO] [UseWarning.Log] {"authorized": ["Tyler\u2019s MacBook Pro", "May\u2019s MacBook Pro", "Bedroom peaker", "May\u2019s iPhone", "XboxOne", "Phone Boy", "Pixel 2", "nothing"], "device": {"id": "15b2f70b7b614dbf3d2bb840169e325bdecd59f5", "is_active": true, "is_restricted": false, "name": "Web Player (Firefox)", "type": "Computer", "volume_percent": 100}, "token": "BQAHJrgvvANGdRAQ_UT-YfyqZtE4ND0EieGOkzb-x8mUAPQv_hpRctFV8QOMQQZ2Zui9HCGWZ569IDLgbkMGQulFGY3r3mHC2uXpCHHxsybriEZBnt91e12N1cmZCZubt_xJIsQEEUdDDOxQQJkIt9B4oNWucrCAMlDqxw9KIbmNe3E"}
[2018-01-17 15:58:59.949] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 15:58:59.958] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 16:00:13.068] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 16:00:13.776] NIO [INFO] [UseWarning.Log] Setting status to configured
[2018-01-17 16:00:13.882] NIO [INFO] [UseWarning.Log] Setting status to starting
[2018-01-17 16:00:13.888] NIO [INFO] [UseWarning.Log] Setting status to started
[2018-01-17 16:00:31.558] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:00:55.527] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:01:07.557] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:01:19.477] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:01:31.598] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:01:43.496] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:01:50.218] NIO [INFO] [UseWarning.Log] Setting status to stopping
[2018-01-17 16:01:50.227] NIO [INFO] [UseWarning.Log] Setting status to stopped
[2018-01-17 16:01:55.645] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 16:01:58.827] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=15b2f70b7b614dbf3d2bb840169e325bdecd59f5 returned with response code: 403
[2018-01-17 16:09:41.227] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
[2018-01-17 16:13:25.091] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:13:37.125] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:13:49.291] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:14:00.947] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:14:14.087] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:14:28.655] NIO [WARNING] [UseWarning.PausePlayback] HTTPMethod.PUT request to https://api.spotify.com/v1/me/player/pause?device_id=5280a2d943ce46a3a590f663b70c81297b83f682 returned with response code: 403
[2018-01-17 16:36:46.985] NIO [INFO] [pubkeeper.protocol.v1] Authenticated to Pubkeeper
